services:
    namenode:
        image: velnae28/hadoop-namenode:${VERSION}
        container_name: namenode
        restart: always
        ports:
            - 9870:9870
            - 9000:9000
        volumes:
            - hadoop_namenode:/hadoop/dfs/name
        environment:
            - CLUSTER_NAME=test
        env_file:
            - ./hadoop.env
        networks:
            - default

    datanode:
        image: velnae28/hadoop-datanode:${VERSION}
        container_name: datanode
        restart: always
        ports:
            - 9864:9864
        volumes:
            - hadoop_datanode:/hadoop/dfs/data
        depends_on:
            - namenode
        environment:
            - SERVICE_PRECONDITION=namenode:9870
            - CLUSTER_NAME=test
        env_file:
            - ./hadoop.env
        networks:
            - default

    datanode2:
        image: velnae28/hadoop-datanode:${VERSION}
        container_name: datanode2
        restart: always
        volumes:
            - hadoop_datanode2:/hadoop/dfs/data
        depends_on:
            - namenode
        environment:
            - SERVICE_PRECONDITION=namenode:9870
            - CLUSTER_NAME=test
        env_file:
            - ./hadoop.env
        networks:
            - default

    datanode3:
        image: velnae28/hadoop-datanode:${VERSION}
        container_name: datanode3
        restart: always
        volumes:
            - hadoop_datanode3:/hadoop/dfs/data
        depends_on:
            - namenode
        environment:
            - SERVICE_PRECONDITION=namenode:9870
            - CLUSTER_NAME=test
        env_file:
            - ./hadoop.env
        networks:
            - default

    resourcemanager:
        image: velnae28/hadoop-resourcemanager:${VERSION}
        container_name: resourcemanager
        restart: always
        ports:
            - 8088:8088
        depends_on:
            - datanode
        environment:
            - SERVICE_PRECONDITION=namenode:9000 namenode:9870 datanode:9864
            - CLUSTER_NAME=test
        env_file:
            - ./hadoop.env
        networks:
            - default

    nodemanager1:
        image: velnae28/hadoop-nodemanager:${VERSION}
        container_name: nodemanager
        restart: always
        ports:
            - 8042:8042
        depends_on:
            - resourcemanager
        environment:
            - SERVICE_PRECONDITION=namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088
            - CLUSTER_NAME=test
        env_file:
            - ./hadoop.env
        networks:
            - default

    historyserver:
        image: velnae28/hadoop-historyserver:${VERSION}
        container_name: historyserver
        restart: always
        ports:
            - 8188:8188  # Puerto para la interfaz web del HistoryServer
        depends_on:
            - resourcemanager
        environment:
            - SERVICE_PRECONDITION=namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088
            - CLUSTER_NAME=test
        volumes:
            - hadoop_historyserver:/hadoop/yarn/timeline
        env_file:
            - ./hadoop.env
        networks:
            - default

volumes:
    hadoop_namenode:
    hadoop_datanode:
    hadoop_datanode2:
    hadoop_datanode3    :
    hadoop_historyserver:

networks:
    default:
        name: docker-hadoop
        external: true